# Debug Docker Compose configuration
# Use: docker compose -f docker-compose.debug.yml up

services:
  pdf-translator:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./data:/app/data
      - model_cache:/home/appuser/.cache
    environment:
      - PDF_TRANSLATE_DEBUG=true
      - PDF_TRANSLATE_HOST=0.0.0.0
      - PDF_TRANSLATE_PORT=8000
      - PDF_TRANSLATE_REDIS_URL=redis://localhost:6379/0
      - PDF_TRANSLATE_DATABASE_URL=sqlite:///./data/jobs.db
      - PDF_TRANSLATE_MODEL_NAME=facebook/mbart-large-50-many-to-many-mmt
      - PDF_TRANSLATE_USE_SAFETENSORS=true
      - PDF_TRANSLATE_CPU_LOAD_THEN_GPU=false
      - PDF_TRANSLATE_MAX_TOKENS_PER_BATCH=32000
    restart: unless-stopped
    command: ["debug"]  # Start in debug mode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  model_cache:
    driver: local
