# Production Docker Compose configuration
# Use: docker compose -f docker-compose.prod.yml up -d

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pdf-translator:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./data:/app/data
      - model_cache:/home/appuser/.cache
    environment:
      - PDF_TRANSLATE_DEBUG=true
      - PDF_TRANSLATE_HOST=0.0.0.0
      - PDF_TRANSLATE_PORT=8000
      - PDF_TRANSLATE_REDIS_URL=redis://redis:6379/0
      - PDF_TRANSLATE_DATABASE_URL=sqlite:///./data/jobs.db
      - PDF_TRANSLATE_MODEL_NAME=facebook/mbart-large-50-many-to-many-mmt
      - PDF_TRANSLATE_USE_SAFETENSORS=true
      - PDF_TRANSLATE_CPU_LOAD_THEN_GPU=true
      - PDF_TRANSLATE_MAX_TOKENS_PER_BATCH=64000
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  redis_data:
    driver: local
  model_cache:
    driver: local
