name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'

jobs:
  test-cpu:
    name: Test Suite (CPU)
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests (CPU mode)
        env:
          CI: true
          PDF_TRANSLATE_DATABASE_URL: sqlite:///./test.db
          PDF_TRANSLATE_REDIS_URL: redis://localhost:6379/15
        run: |
          python run_tests.py
          
      - name: Run linting
        run: |
          python run_tests.py --lint
          
  test-docker:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Build Docker image
        run: |
          docker build -t translate-pdfs:test .
          
      - name: Test Docker image
        run: |
          docker run --rm translate-pdfs:test bash -c "python -c 'import src.main; print(\"Build successful!\")'"
          
      - name: Run tests in container
        run: |
          docker run --rm -e CI=true translate-pdfs:test test
          
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install safety
        run: pip install safety
        
      - name: Run security scan
        run: safety scan -r requirements.txt --continue-on-vulnerability-error
        
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install code quality tools
        run: |
          pip install black isort flake8 mypy
          
      - name: Check code formatting
        run: |
          black --check src/ tests/ main.py
          isort --check-only src/ tests/ main.py
          
      - name: Run linting
        run: |
          flake8 src/ tests/ main.py
          
      - name: Run type checking
        run: |
          mypy src/ --ignore-missing-imports
